[package]
name = "rust-image-service"
version = "0.1.0"
edition = "2021"

[dependencies]
opencv = { version = "0.91.3", features = ["imgproc"] }
actix-web = "4"
actix-cors = "0.6.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

base64 = "0.12.3"
image = "0.23"